### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PhilipMathieu** [ds5010/vaccines#67]
Maybe we start listing things we want to work on here and try to assign tasks within the next few days?

**Comment by PhilipMathieu** [comment]
Some possible tasks (may not need all of these):

- Resolve legend issues #59 
- Create subset of data for unittests
- Scaffold unittests (i.e., look up best practices for folder/file/module structure and set it up)
- Unittests for each of the Phase I Roadmap main tasks
- Add regression line enhancement to Phase I graph
- Incorporate Bridget's code and refactor/make modular
- Increase time-resolution across the board
- Reconfigure code to use return values instead of intermediary files (or add arguments so it becomes an option)

**Comment by PhilipMathieu** [comment]
This may be helpful for the pages part of the project: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

**Comment by MatthewjRay** [comment]
> This may be helpful for the pages part of the project: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

Thanks for sharing, Philip. I can take a look into setting up a Github Page this evening.

**Comment by PhilipMathieu** [comment]
I managed to get ahead on my work hours this week for my day job so I'll have a bit of time this afternoon to work on this. I'm planning to scaffold out the unittest directory. Is anyone else already working on that?

**Comment by PhilipMathieu** [comment]
- [x] https://github.com/ds5010/vaccines/issues/59
- [ ] Create subset of data for unittests
- [x] Scaffold unittests (i.e., look up best practices for folder/file/module structure and set it up)
- [ ] Unittests for each of the Phase I Roadmap main tasks
- [x] Add regression line enhancement to Phase I graph
- [ ] Incorporate Bridget's code and refactor/make modular
- [ ] Increase time-resolution across the board
- [ ] Reconfigure code to use return values instead of intermediary files (or add arguments so it becomes an option)

**Comment by sophiacofone** [comment]
I am trying to work on making a unittest for the animation/image naming convention that we settled on. 
Question about the "Increase time-resolution across the board" point, what exactly are we attempting to do here? Are we trying to do every 2 weeks instead of every month for the snapshot, or am I thinking of time-resolution incorrectly?

**Comment by PhilipMathieu** [comment]
I think that was the idea, but it may not be a priority

**Comment by PhilipMathieu** [comment]
I *think* this is all we had from class:

- [ ] Create a .gitignore file to deal with data source and misc files (e.g., .DS_Store) -- kayne
- [ ] Distinguish data download/provenance from analysis/cleaning -- ???
- [ ] Clean up "make test" Makefile and unused code -- yune & jerry
- [ ] Integrate the new visualization software -- bridget
- [ ] Check to see if the viz code could be more concise - philip
- [ ] gh-pages site -- add the new visuals - matt & sophia
- [ ] Update the gh-pages story - matt & sophia

I would also suggest we add the following if anyone has time (feel free to add):
- [ ] Comment all modules
- [ ] Reorganize/consolidate makefile -- philip

**Comment by PhilipMathieu** [comment]
Closed by #94
